import { Inject, Injectable } from '@nestjs/common';
import { FamilyEncryptionKey } from '@prisma/client';
import { LEO_PRISMA_CLIENT } from '../prisma-client.provider';
import type { PrismaClientLike } from './types';

// M18 — the per-Family DEK envelope (data-classification-and-
// isolation.md §5.2, filled in for the first time by this milestone;
// see schema.prisma's FamilyEncryptionKey comment and
// leo.config.ts's header for the dev-only-stopgap disclaimer this
// table's contents are subject to). Repository-layer only, consumed
// exclusively by leo-encryption.service.ts — never by a controller,
// never through the RLS-bounded role (this table's migration grants
// natkhat_app_role nothing at all).
@Injectable()
export class FamilyEncryptionKeyRepository {
  constructor(@Inject(LEO_PRISMA_CLIENT) private readonly prisma: PrismaClientLike) {}

  findByFamilyId(familyId: string): Promise<FamilyEncryptionKey | null> {
    return this.prisma.familyEncryptionKey.findUnique({ where: { familyId } });
  }

  // Explicitly Uint8Array<ArrayBuffer>, not bare Uint8Array — this
  // codebase's ambient lib types default a bare Uint8Array/Buffer
  // annotation to the wider Uint8Array<ArrayBufferLike>/
  // Buffer<ArrayBufferLike>, which Prisma's generated Bytes-column
  // input type (Uint8Array<ArrayBuffer> specifically) then rejects.
  // Every real value passed in here (Buffer.concat/randomBytes output)
  // already satisfies the narrower form at runtime; this only makes
  // the type checker agree.
  create(data: {
    familyId: string;
    wrappedDek: Uint8Array<ArrayBuffer>;
  }): Promise<FamilyEncryptionKey> {
    return this.prisma.familyEncryptionKey.create({ data });
  }

  /**
   * ai-memory-isolation.md §7.5 — crypto-shredding: destroying the
   * wrapped DEK irreversibly destroys every Tier-3 row encrypted under
   * it. Physical delete, not tombstone, deliberately — a destroyed key
   * has no PII to scrub, and leaving the (now-undecryptable) row
   * around serves no retention purpose; this mirrors
   * audit_event.purgeExpired's "no PII, so physical removal is
   * correct" reasoning, applied here to key material instead of
   * content-free log rows. Consumed by lifecycle.service.ts's
   * hard-delete sweep at the point a Family completes its own
   * hard-delete (§7.5's stated trigger), not at soft-delete time.
   */
  async deleteByFamilyId(familyId: string): Promise<boolean> {
    const result = await this.prisma.familyEncryptionKey.deleteMany({ where: { familyId } });
    return result.count > 0;
  }
}
