import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import './globals.css';

export const metadata: Metadata = {
  title: 'Natkhat AI — Admin',
  description: 'Internal admin console (Sprint 04 M22 scaffold, synthetic data only).',
};

// Not typed via Next's generated `LayoutProps<'/'>` global — that type
// only exists after `.next/types` has been generated by a build, and
// this repo's `typecheck` Turborepo task deliberately does not depend
// on `build` (turbo.json), so `tsc --noEmit` must be able to pass
// standalone.
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
